#!/bin/bash

set -e

DIR=$(dirname $(realpath "$0"))

bver=6.24

if [ -n "$1" ] ; then
  if [[ $1 =~ rc[0-9] ]] ; then
    pkgver=${bver}$1
  else
    pkgver=${bver}+dev$1
  fi
else
  pkgver=${bver}+dev$(date +'%m%d')
fi

file=("reaper${pkgver//.}_linux_x86_64.tar.xz")
echo $file
url=("https://www.landoleet.org/$file")

pushd $DIR
  sed -i "s/^\(pkgver=\).*/\1${pkgver}/" $DIR/PKGBUILD
  wget -v -nc $url -P $DIR
  sha=$(sha256sum $DIR/$file | awk '{print $1}')
  sed -i "s/^\(sha256sums=\).*/\1('${sha}')/" $DIR/PKGBUILD
  makepkg -si
  cp /var/cache/pacman/pkg/reaper-bin-dev-${pkgver}-1-x86_64.pkg.tar.zst ~/SyncLinux/
popd
